[workspace.package]
name = "v3"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "pool",
    "bindings",
]

default-members = [
    "pool",
    "bindings",
]

[workspace.dependencies]
bindings = { path = "./bindings" }
pool = { path = "./pool" }